name: CI
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'
            - run: npm ci
            - run: npm run test:lint
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'
            - run: npm ci
            - run: npm run build
            - uses: actions/upload-artifact@v4
              with:
                  name: built
                  path: ./dist
                  retention-days: 1
    types:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'
            - uses: actions/download-artifact@v4
              with:
                  name: built
                  path: ./dist
            - run: npm ci
            - run: npm run test:types
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'
            - uses: actions/download-artifact@v4
              with:
                  name: built
                  path: ./dist

            - run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV
            - name: Cache playwright binaries
              uses: actions/cache@v4
              id: playwright-cache
              with:
                  path: |
                      ~/.cache/ms-playwright
                  key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
            - run: npm ci
            - run: npx playwright install --with-deps chromium
              if: steps.playwright-cache.outputs.cache-hit != 'true'

            - run: npm run test:ci
    size:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'
            - uses: actions/download-artifact@v4
              with:
                  name: built
                  path: ./dist
            - run: npm ci
